# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "ws-8.8.1" = {
      name = "ws";
      packageName = "ws";
      version = "8.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.8.1.tgz";
        sha512 = "bGy2JzvzkPowEJV++hF07hAD6niYSr0JzBNo/J29WsB57A2r7Wlc1UFcTR9IzrPvuNVO4B8LGqF8qcpsVOhJCA==";
      };
    };
  };
  args = {
    name = "ln-ws-proxy";
    packageName = "ln-ws-proxy";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."ws-8.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ln-ws-proxy";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
