# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bufferutil-4.0.8" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.8.tgz";
        sha512 = "4T53u4PdgsXqKaIctwF8ifXlRTTmEPJ8iEPWFdGZvcf7sbwYo6FKFEX9eNNAnzFZ7EzJAQ3CJeOtCRA4rDp7Pw==";
      };
    };
    "node-gyp-build-4.8.1" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.1.tgz";
        sha512 = "OSs33Z9yWr148JZcbZd5WiAXhh/n9z8TxQcdMhIOlpN9AhWpLfvVFO73+m77bBABQMaY9XSvIa+qk0jlI7Gcaw==";
      };
    };
    "utf-8-validate-6.0.4" = {
      name = "utf-8-validate";
      packageName = "utf-8-validate";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-6.0.4.tgz";
        sha512 = "xu9GQDeFp+eZ6LnCywXN/zBancWvOpUMzgjLPSjy4BRHSmTelvn2E0DG0o1sTiw5hkCKBHo8rwSKncfRfv2EEQ==";
      };
    };
    "ws-8.18.0" = {
      name = "ws";
      packageName = "ws";
      version = "8.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-8.18.0.tgz";
        sha512 = "8VbfWfHLbbwu3+N6OKsOMpBdT4kXPDDB9cJk2bJ6mh9ucxdlnNvH1e+roYkKmN9Nxw2yjz7VzeO9oOz2zJ04Pw==";
      };
    };
  };
  args = {
    name = "ln-ws-proxy";
    packageName = "ln-ws-proxy";
    version = "0.1.0";
    src = ./.;
    dependencies = [
      sources."bufferutil-4.0.8"
      sources."node-gyp-build-4.8.1"
      sources."utf-8-validate-6.0.4"
      sources."ws-8.18.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ln-ws-proxy";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
